version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
      - hivemq
    restart: always

  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    restart: always

  hivemq:
    build:
      context: ./hivemq
      dockerfile: Dockerfile
    container_name: hivemq
    ports:
      - "1883:1883"
      - "8000:8000"
      - "8081:8081"
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "1883:1883"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
